#!/bin/bash
### BEGIN INIT INFO
# Provides:          dbus-shelly-inverter
# Required-Start:    $remote_fs $syslog $network
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start the Python script as a service
# Description:       Manage the dbus-shelly-plug-inverter.py script
### END INIT INFO

WORKING_DIR="/data/dbus-shelly-plug-inverter"
SCRIPT="/data/dbus-shelly-plug-inverter/dbus-shelly-plug-inverter.py"
RUNAS="root"

PIDFILE="/var/run/dbus-shelly-inverter.pid"
LOGFILE="/var/log/dbus-shelly-inverter.log"

start()
{
    if [ -f "$PIDFILE" ] && kill -0 $(cat "$PIDFILE"); then
        echo 'Service already running' >&2
        return 1
    fi
    echo "Starting service…" >&2
    cd $WORKING_DIR
    local CMD="python $SCRIPT &> \"$LOGFILE\" & echo \$!"
    su -c "$CMD" $RUNAS > "$PIDFILE"
    echo "Service started" >&2
}

stop()
{
    if [ ! -f "$PIDFILE" ] || ! kill -0 $(cat "$PIDFILE"); then
        echo 'Service not running' >&2
        return 1
    fi
    echo 'Stopping service…' >&2
    kill -15 $(cat "$PIDFILE") && rm -f "$PIDFILE"
    echo 'Service stopped' >&2
}

status()
{
    if [ -f "$PIDFILE" ] && kill -0 $(cat "$PIDFILE"); then
        echo 'Service is running' >&2
        return 0
    fi
    echo 'Service is not running' >&2
    return 1
}

case "$1" in
  start)
    start
    ;;
  stop)
    stop
    ;;
  status)
    status
    ;;
  restart)
    stop
    start
    ;;
  *)
    echo "Usage: $0 {start|stop|status|restart}"
esac
